Document: hpp
Title: Debian hpp Manual
Author: <insert document author here>
Abstract: This manual describes what hpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hpp/hpp.sgml.gz

Format: postscript
Files: /usr/share/doc/hpp/hpp.ps.gz

Format: text
Files: /usr/share/doc/hpp/hpp.text.gz

Format: HTML
Index: /usr/share/doc/hpp/html/index.html
Files: /usr/share/doc/hpp/html/*.html

  
